name: build-and-deploy-dev
on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  GITHUB_USER: ${{ github.repository_owner }}
  IMAGE_NAME: "alex-brot-backend"
  REGISTRY: "ghcr.io"

permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Only on dev brach
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.7.0

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/main/docker/Dockerfile.jvm
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: |
            ${{ env.REGISTRY }}/${{ env.GITHUB_USER }}/${{ env.IMAGE_NAME }}:dev-${{ github.run_number }}

      - name: Checkout k8s Repo
        uses: actions/checkout@v4
        with:
          repository: alex-brot/k8s-deployments

      - name: Modify file
        run: |
          sed -i 's|\(image: ghcr.io/alex-brot/alex-brot-backend\\:\).*|\1${{ env.TAG }}|' ./alex-brot/overlays/dev/kustomization.yaml

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./alex-brot/overlays/dev/kustomization.yaml
          git commit -m "Automated image version bump to ${{ env.TAG }}"
          git config --unset-all http.https://github.com/.extraheader
          git push https://${{ secrets.K3S_REPO_PAT }}@github.com/alex-brot/k8s-deployments.git