on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: quarkus
          POSTGRES_PASSWORD: quarkus
          POSTGRES_DB: quarkus_test_db
        options: >-
          --health-cmd "pg_isready -U quarkus
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5"

    env:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: quarkus
      DB_PASSWORD: quarkus
      DB_NAME: quarkus_test_db

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up Kotlin
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Make Gradlew executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test
